apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
data:
  DATABASE_URL: "jdbc:postgresql://postgres.platform-services:5432/social_posts"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.platform-services:9092"
  KAFKA_POST_EVENTS_TOPIC: "post-events"
  POST_SERVICE_SERVER_PORT: "8992"