spring:
  application:
  name: graph-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: graph-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    listener:
      ack-mode: record

  neo4j:
    uri: ${NEO4J_URI:bolt://127.0.0.1:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:neo4j@123}

graph:
  impl: ${GRAPH_IMPL:neo4j}

app:
  kafka:
    topics:
      user-events: user-events
      post-events: post-events
      notification-events: notification-events

gremlin:
  host: ${GREMLIN_HOST:localhost}
  port: ${GREMLIN_PORT:8182}
  username: null
  password: null
  ssl: false

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN

server:
  port: ${GRAPH_SERVICE_SERVER_PORT:8992}