spring:
  application:
  name: graph-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: graph-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    listener:
      ack-mode: record

app:
  kafka:
    topics:
      user-events: user-events
      post-events: post-events
      notification-events: notification-events

gremlin:
  host: localhost
  port: 8182
  username: null
  password: null
  ssl: false

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN

server:
  port: ${GRAPH_SERVICE_SERVER_PORT:8992}