spring.application.name=graph-service


gremlin:
host: localhost
port: 8182
username: null
password: null
ssl: false

logging:
level:
root: INFO
pattern:
console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
