apiVersion: v2
name: app-services
description: Umbrella chart for all application microservices
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: api-gateway
    version: 1.0.0
    repository: "file://charts/api-gateway"

  - name: auth-service
    version: 1.0.0
    repository: "file://charts/auth-service"

  - name: post-service
    version: 1.0.0
    repository: "file://charts/post-service"

  - name: notification-service
    version: 1.0.0
    repository: "file://charts/notification-service"

  - name: ws-notification
    version: 1.0.0
    repository: "file://charts/ws-notification"

