spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  profiles:
    active: default
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8991}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 10

            - id: graph-service
              uri: ${GRAPH_SERVICE_URL:http://localhost:8992}
              predicates:
                - Path=/graph/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            - id: post-service
              uri: ${POST_SERVICE_URL:http://localhost:8993}
              predicates:
                - Path=/post/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 15
                    redis-rate-limiter.burstCapacity: 30

            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8994}
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40

            - id: ws-notification
              uri: ${WS_NOTIFICATION_URL:ws://localhost:8995}
              predicates:
                - Path=/ws/notification/**
              filters:
                - StripPrefix=2
#                - AddRequestHeader=X-User-Id, {request.headers['X-User-Id']}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
      enabled: true

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

jwt:
  secret: ${JWT_RSA_PUBLIC_KEY}
  header: Authorization
  prefix: Bearer

server:
  port: ${API_GATEWAY_SERVICE_SERVER_PORT:8990}

logging:
  level:
    root: INFO
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: DEBUG

